spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

jwt:
  secret : fgjansrglkasjhflwiaqefhnalskdgfwaerligubasdflkgjher